Repository MateusCMartins724/MauaSalas-ProjetoIntegrador, pull requests merged in 2023-05, with the labels that each got.

#5 #1 Criação do sistema de login
  .gitignore
  app.js
  authConfig.js
  bin/www
  fetch.js
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/auth.js
  routes/index.js
  routes/users.js
  routes/wellKnown.js
  views/error.hbs
  views/id.hbs
  views/index.hbs
  views/layout.hbs
Labels: enhancement

#6 #37 Correção de Bug
  routes/index.js
  views/layout.hbs
Labels: bug

#11 #2 O site redireciona para a API da Microsoft
  routes/auth.js
Labels: bug

#22 #27 Finalizacao do Pagination
  public/javascripts/salasFront.js
  views/manterSalas.hbs
Labels: enhancement

#23 #28 Criação de um Modal para adicionar salas
  views/manterSalas.hbs
Labels: enhancement

#24 #4 Aplicação de métodos para se aplicar à LGPD
  html/adminPage.html
  views/layout.hbs
Labels: enhancement

#25 #42 Finalização do design da tela de usuários conectados
  html/ManterSalas.html
  html/homepage-logado.html
  public/stylesheets/stylesHomePage.css
Labels: enhancement

#26 #42 Implementação da Homepage logado
  app.js
  html/homepage-logado.html
  routes/index.js
  views/index.hbs
Labels: enhancement

#29 #44 Correção conexão MySQL
  conector.js
Labels: bug

#31 #45 - Correção de Bug
  routes/auth.js
Labels: bug

#38 #47 BUG - Manter Admins
  routes/admin.js
  routes/salas.js
Labels: bug

#39 #51 Optimização da renderização do site
  public/images/imagem1.avif
  public/images/imagem1.jpg
  public/images/imagem2.avif
  public/images/imagem2.jpg
  public/images/imagem3.avif
  public/images/imagem3.jpg
  public/images/imagem4.avif
  public/images/imagem4.jpg
  views/index.hbs
Labels: enhancement

#40 #52 Criar sistema para notificação dos usuários via email
  mailer.js
  package-lock.json
  package.json
Labels: enhancement

#43 #53 Restrição de Acesso somente à usuários
  authConector.js
  public/javascripts/adminFront.js
  public/javascripts/blocosFront.js
  public/javascripts/salasAlunoFront.js
  public/javascripts/salasFront.js
  routes/admin.js
  routes/auth.js
  routes/salas.js
  views/manterAdministradores.hbs
Labels: bug, enhancement

#44 #53 Restrição de Acesso somente à usuários
  routes/salas.js
Labels: bug

#45 #53 Restrição de Acesso somente à usuários
  public/javascripts/salaAlunoFront.js
  routes/salas.js
Labels: bug

#46 #52 Criar sistema para notificação dos usuários via email
  public/javascripts/adminFront.js
  routes/admin.js
  views/manterAdministradores.hbs
Labels: enhancement

#47 #46 Correcao de bugs
  conector.js
Labels: bug

#49 #53 Restrição de Acesso somente à usuários autorizados
  authConector.js
Labels: bug

#50 #52 Criação do Sistema de Exemplo Calendário
  calendar.js
  package-lock.json
  package.json
  views/error.hbs
Labels: bug, enhancement
